#!/usr/bin/env bash

CURRENT_TOP_LEVEL_DIR_PATH="$(git rev-parse --show-toplevel)"
cd "$CURRENT_TOP_LEVEL_DIR_PATH" || exit 1

echo "Executed SpotlessCheck"
./gradlew spotlessKotlinCheck --daemon
SPOTLESS_CHECK_RESULT=$?

printf "Executed spotlessKotlinApply"
./gradlew spotlessKotlinApply --daemon

if [ $SPOTLESS_CHECK_RESULT -eq 0 ]; then
  printf ">>> Success\n"
  exit 0
else
  printf ">>> Failed\n"
  exit $SPOTLESS_CHECK_RESULT
fi
